while True:
  print("ESCAPE")
  print("Welcome!")
  n1=input("Choose the name of your first character: ")
  n2=input("Choose the name of your second character: ")
  n3=input("Choose the name of your third character: ")
  n4=input("Choose the name of your fourth character: ")
  n5=input("Choose the name of your fifth character: ")
  print("Let's stars the GAME! ")

  input()
  
  print(n1,": Hi, my characteristics are: strong, optimistic and leader.")

  print(n2,": Hello, my characteristics are: smart, agile, and energetic. ")

  print(n3,": Hey! my characteristics are:kind,shy and fearfull")

  print(n4,": Whats up! my characteristics are: dumb, simpatic, and i love animals.")

  print(n5,": Hi my characteristics are: creative,  ")

  input()
  
  print(n1, ": We've been here for a long time, we're already running out of food... WE NEED TO GET OUT OF HERE")

  input()
  
  print("Your mission is to get them out, whitout anyone diying, by finding the password.")

  input()

  print(n2, ": Guys, I have heard that on this island, those who had tried to escape, had not survived...")
  input()
  
  print(n3, ": Guys! Come on, i found something!")
  input()
  print(n2, ": Omg, What is that? Is that a gun?")
  input()
  print(n5, ": I think so...")
  input()
  gun=("ᡕᠵ᠊ᡃ່࡚ࠢ࠘⸝່ࠡࠣ᠊߯᠆ࠣ࠘ᡁࠣ࠘᠊᠊ࠢ࠘𐡏")
  print("YOU FOUND A GUN", gun)

  input()
  
  print(n2, ": This will help us later")

  input()

  print(n1, ": We need to get some food now!, i think i saw an animal before...")

  input()

  print(n4, ": No, we are not killing any animal, we are going to find another thing to eat, but not an animal!")

  input()

  print("What are you going to do?...")

  input()

  elige = input("-K- if you want to kill the animal or -S- if you want to search")
  
  if (elige=="K"):
    print(gun)
    input()
    print (n4, ": NOOO, why you did that, i'm not gonna eat that 😡")
    input()
    print (n1, ": if you dont want to eat this, you are going to die")
    input()
    print (n5, ": WE ONLY HAVE THIS")
    input()
    print (n4, ": Ok, im going to eat a little bit but only for this time, next time we search for other thing ")
    input()
    print (n1, ": Ok just eat, in the morning we are going to look for the first game ")
    input()
    print(n3, ": Goodnight ")
    input()
    print("THE NEXT MORNING")
    input()
    print(n2, ": WAKE UP")
    input()
    print(n1, ": Come on, we need to look for the first game")
    input()
    print(n4, ": Im not happy about last night but now i have energy")
    input()
    print("A FEW HOURS LATER")
    input()
    print(n4, ": Heyy, i think i found something")
    input()
    print(n5, ": Omg it's the first game")
    input()
    print("THE FIRST GAME")
    input()
    while True:
      adivina=int(input("Insert a number:"))
      if adivina < 10:
        print('You are missing a lot')
      if adivina > 150:
        print ('You passed a lot ')
      if adivina >= 56:
        print ('You passed')
      if adivina <= 54:
        print('You miss ')
      if adivina ==55:
        print('YOU WIN!')
        break
    print("THE FISRT LETTER IS *E*")
    print("E_____")
    input()
    print(n1, ": Omg we have the first letter")
    input()
    print(n4, ": Im so excited")
    input()
    print(n3, ": Yess!, we miss 5 letters ")
    input()
    print(n5, ": How do you find that?", n4)
    input()
    print(n4, ": I dont know, I only found something different")
    input()
    print(n1, ": Now we need to search for more food and the other games ")
    input()
    print(n4, ":I think I see some food there, and is not an animal")
    input()
    print(n5, ": We need food ")
    input()
    print(n3, ": Lets go!")
    input()
    print(n1, ": Come on, we dont have enough time, Im starving and im thirsty")
    input()
    print(n2, ": There are coconuts")
    input()
    print(n5, ": Delicious, i love cocos")
    input()
    print(n1, ": Omg thanks god some food")
    input()
    print(n3, ": Oh no, there is only 4 cocos, what are we going to do?")
    input()

    while True:
      coco=input("-1- if only four eat and one dont, -2- if they share the cocos ")
      if (coco=="2"):
        print(n2, ": That is a good idea")
        input()
        print(n5, ": Yes, now every one can eat")
        input()
        print(n1, ": Can i eat? im starving ")
        input()
        print(n2, ": Yeah me too")
        input()
        print(n4, ": This is delicious")
        input()
        print(n3, ": The coconut water is delicous too")
        input()
        print(n1, ": Yes, and is refresh ")
        input()
        print("ALL EAT...")
        input()
        print(n2, ": I'm still hungry")
        input()
        print(n4, ": I'm ok, i can survive with that ")
        input()
        print(n1, ": I have an idea ")
        input()
        print(n2, ": What is your idea?")
        input()
        print(n1, ": We can separate")
        input()
        print(n5, ": Mmm how, that a crazy idea ")
        input()
        print(n4, ": Yes, we are in an island in the middle of nothing ")
        input()
        print(n1, ": Let me talk please ")
        input()
        print(n2, ": Ok sorry")
        input()
        print(n1, ": We can separate in groups, me with ", n2, "to search for food and water and the others can go to find the second letter ")
        input()
        print(n2, ": I like that idea, and i can eat and drink water")
        input()
        print(n1, ": What do you think? ")
        input()
        print(n5, ": I like that idea too")
        input()
        print(n4, ": Yeahh me too")
        input()
        print(n3, ": Well if everyone wants, i agree")
        input()
        print(n1, ": Well lets go", n2)
        input()
        print(n2, ": YESS, bye losers, if i find food i am going to eat all")
        input()
        print(n4, ": That is not fair")
        input()
        print(n3, ": Bye good luck ")
        input()
        print(n5, ": Calm, he is not going to eat all, he is joking BYEE")
        input()
        print("EVERYONE GO TO EACH COURSE")
        input()
        print(" 1 HOUR LATER")
        input()
        print(n1, ": Hey! there is water and food there ")
        input()
        print(n2, ": Omg!! finally, i am starving")
        input()
        print(n1, ": Oh oh :/")
        input()
        print(n2, ": WHAT?")
        input()
        print(n1, ": It is very little food ")
        input()
        print(n2, ": What are we going to do, it will not be enough for everyone")
        input()
        while True:
          eat=input("1 if they are going to eat the food or 2 if they wait for everyone")
          if (eat=="1"):
            print(n1, ": lets eat and dont tell the others")
            input()
            print(n2, ": Yes, im really hungry")
            input()
            print(n1, ": It is only a little ")
            input()
            print(n2, ": When we found them we need to say that we dont found anything")
            input()
            print(n1, ": Yes yes, but i feel a little guilty")
            input()
            print(n2, ": But if we dint eat we could die and is only a little ")
            input()
            print(n1, ": Ok that is right ")
            input()
            print(n2, ": Well lets go we dont found anything")
            input()
            print(n1, ": Yes")
            input()
            print("WHEN THEY ARE WALKING TO GO BACK THE OTHERS FOUND SOMETHING")
            input()
            print(n3, ": Heyy i think there is food and water there and is a lot, and something weird")
            input()
            print(n4, ": We can save food for the others ")
            input()
            print(n5, ": OMGG the other letter ")
            input()
            print(n3, ": There is no game!")
            input()
            print(n5, ": HEYY there are  two letters together! ")
            input()
            print("THE ONLY RULE TO TAKE IT IS TO SAVE THE LETTER IN THE CHEST WITH A RANDOM PASSWORD ")
            input()
            print("ESC____!")
            input()
            print("MAKE A PASSWORD")
            import random 

            base="escape"
            
            passw=""

            lon=int(input("select the lenght of the password: "))

            for i in range (lon):
                passw=passw+random.choice(base)
    
            print("password:", passw)


            print(n4, ": FINALLY we have 3 letters ")
            input()
            print(n3, ": There are the guys")
            input()
            print(n2, ": HIII we found you")
            input()
            print(n5, ": Omg hi, do you find food?")
            input()
            print(n1, ": No, we dont find ")
            input()
            print(n5, ": Uh, I thought you found something")
            input()
            print(n2, ": No we dont")
            input()
            print(n4, ": Well we find food and water")
            input()
            print(n1, ": Omg really")
            input()
            print(n3, ": Take it, we keep you a little of food")
            input()
            print(n1, ": Umm we need to tell something")
            input()
            print(n5, ": What??")
            input()
            print(n2, ": We found a little bit of food but we eat it")
            input()
            print(n4, ": Why would you do that?")
            input()
            print(n1, ": SORRY it was only a little and we were starving")
            input()
            print(n3, ": We save food and we you find you eat")
            input()
            print(n5, ": That is not fair")
            input()
            print(n1, ": I am really sorry")
            input()
            print(n4, ": Stop we need to find more clues and you are only arguing")
            input()
            print(n1, ": Yes, we need to stop, we are friends")
            input()
            print(n2, ": This is not going to happen again, we are really sorry ")
            input()
            print(n4, ": Ok, we are really close to escape!")
            print(n3, ": What letters do we have?")
            input()
            print(n2, ": We have 3, ESC")
            input()
            print(n5, ": And if we try to guess the word?")
            input()
            print(n1, ": No, lets search one more and then we try")
            input()
            print("THEY CONTINUE LOOKING FOR LETTERS")
            input()
            print(n3, ": Hey guys, there is a lake over there")
            input()
            print(n3, ": I think there is something in the water")
            input()
            print(n1, ": I can swim amd get it")
            input()
            print(n3, ": Yes that is a good idea")
            input()
            print(n1, ": It is another letter!")
            input()
            print("ESCA__")
            input()
            print(n5, ": Only 2 more letters")
            input()
            print(n4, ":Lets try to guess the word ")
            input()
            print(n5, "I think is very easy to guess it")
            print(n1, "Lets try")
            input()
            guess="hola"
            while(guess!="ESCAPE"):
              guess=input("Guess:")
              if guess!="ESCAPE":
                print("Try again!")
            
            print("YOU WINNN!")
            break
              
              
            
            
            
            
            

            
            
            break
            
          if (eat=="2"):
            print(n1, ": Lets wait if we find more ")
            input()
            print(n2, ": Okey")
            input()
            print("THEY CONTINUE SEARCHING")
            input()
            print(n1, ": hey, we have like 3hrs seraching and we dont find anything")
            input()
            print(n2, ": I am really hungry")
            input()
            print(n1, ": Me too and i feel tired")
            input()
            print(n2, ": We can sleep for 15min")
            input()
            print(n1, ": Yess")
            input()
            print("THEY FALL A SLEEP")
            input()
            print("THEY DONT WAKE UP")
            input()
            print("YOU LOOSE")
            continue

          
        
        break
      if (coco=="1"):
        print(n1, ":And who is the one that is not getting the coco?")
        input()
        print(n3, ":We should do a giveaway...")
        input()
        print(n4, ":Ok, i agree")
        input()
        print(n1, ":Im going to do the papers")
        print("10 MINUTES LATERS")
        input()
        print(n1, ":I have the papers, im going to get one without seeing...")
        input()
        input()
        print(n1, ":The one that is not getting a coco is...")
        input()
        print(n1, ":ME?")
        input()
        print(n2, ":Im so sorry...")
        input()
        print(n3, ":Come on, if you can, don't think about food or drink, we all have to survive, I know we'll find something")
        input()
        print(n5, ":Yes, we can")
        input()
        print(n1, ":Omg no, im going to die, I DONT WANT TO DIE!!")
        input()
        print(n2, ":CHILL OUT")
        input()
        print(n3, ":Shut up, and let's drink the cocos")
        input()
        print("EVERYBODY DRINKS THE COCOS")
        input()
        print(n1, ":I'm very thirsty, I don't know if I'm going to be able to survive")
        input()
        print(n2, ":Im sure we are going to find something")
        input()
        print(n3, ":Let's go searching again!")
        input()
        print(n5, ":Yes!, but let's go all togehter")
        input()
        print(n2, ":Ok, I agree")
        input()
        print("1 HOUR LATER")
        input()
        print(n1, ":Help, please, im so tired!")
        input()
        print(n2, ":Hey, I don't know if it's me, but he looks very pale...")
        input()
        print(n4, ":Do not exaggerate")
        input()
        print(n3, ":I dont think he is exaggerating...")
        input()
        print(n1, "DIED")
        input()
        print("SORRY YOU LOST")
        input()
    
        continue
    
  elif (elige=="S"):
    print(n1, ": We are going to die!")
    input()
    print(n2, ": I think we should split us to find food")
    input()
    print(n1, ": Okey, but im not going with" ,n4)
    input()
    print(n3, ": I want to be with" ,n4)
    input()
    print(n5, ": I want to be with you too")
    input()
    print(n1, ": Okey, perfect, i will be with", n2)
    input()
    print(n2, ": Perfect 👍🏻")
    input()
    print(n1, ": Let's go", n2)
    input()
    print("3 HOURS LATER")
    input()
    print(n1, ": Im very hungry, we didn't find ANYTHING! ... I would have killed that animal")
    input()
    print(n4, ": It' getting dark, im starving ")
    input()
    print(n1, ": It's your fault...")
    input()
    print(n3, ": STOP FIGHTING! Let's go to sleep, and tommorow will continue looking for food") 
    input()
    print(n5, ": I agree")
    input()
    print("EVERYBODY GOES TO SLEEP")
    input()
    print("They all starved to death... ")
    input()
    print("-SORRY, TRY AGAIN!-")