print("what's your name?")
nombre=input()
print("whats up", nombre)
print("where do you live")
vives=input()
print("i like that place!")
print("and what do you like to do")
hacer=input()
print("really? me too")
print("how old are you")
años=input()
print("wow you are very old")
print("and do you have siblings?")
hermanos=input()
print("what is your favorite color?")
color=input()
print("that color is beatiful!")
print("do you like to stay at home or go to party?")
fiesta=input()
print("i like that too!")
print("when is your birthday!")
cumple=input()
print("it's almost your birthday")
print("what is your favorite sport?")
deporte=input()
print("that sport is so fun!")
print("you have a boy/girlfriend?")
boy=input()
print("oh")